### ISSUE TITLE
Make compiling a C extension optional

### ISSUE THREAD

**Issue by sametmax** [rfk/playitagainsam#12]
It would be great to have a pure Python pias that you can install without compiling anything, even if it means less features. I don't know what psutil is used for, but maybe there is an alternative to it, or maybe you can just make it an optional dependancy and allow to use pias in a limited way without it with a conditional import.

This would have 2 benefits: 

- much easier to install. Plenty of newcomers have no idea that they need to install Python headers and a compiler, or even what it is.
- you can then add stand alone session file.

Let me explain the last point : sometime you want to send a session to someone, but you don't want them to have to install pias. For students, maybe they just never heard of pip yet, or maybe they are learning bash/lisp/ruby, and don't care about Python.

if pias didn't have a compiled  dependancie, we could just zip pias with the session and send it by email to student, that can run it without knowing how it works.

**Comment by mhRoh** [comment]
Dear Ryan Kelly.
Your Playitagainsam solved one of my problems. I really appriceate it.
I test your project on AIX 5.3 TL 12 Server. But It has a dependency problem cause
PSUTIL dosen't support AIX5. So I have to change util.py as belows.

try:
    import psutil
except ImportError:
    psutil = None

def get_ancestor_processes():
    """Get a list of the executables of all ancestor processes."""
    if psutil is None:
        pass
    elif not _ANCESTOR_PROCESSES:
        proc = psutil.Process(os.getpid())
        while proc.parent() is not None:
            try:
                _ANCESTOR_PROCESSES.append(proc.parent().exe())
                proc = proc.parent()
            except psutil.Error:
                break
    return _ANCESTOR_PROCESSES

I think you've already known about this issue. How about apply  codes in next version of PIAS

**Comment by rfk** [comment]
I added a variant of your fix in https://github.com/rfk/playitagainsam/commit/bbfab1144e5db015eed29523b61b10d207828a39.  Can you please try out the latest version from github and let me know if it works for you?  It all seems well I'll cut a new release.

**Comment by mhRoh** [comment]
It works fine on AIX5.3 TL12.
Thank you.

**Comment by rfk** [comment]
Thanks, I've released v0.4.0 with this fix
