### ISSUE TITLE
Support for time difference between commands

### ISSUE THREAD

**Issue by KK143** [rfk/playitagainsam#18]
Hi,
Do we have any support for the time difference taken into account so that it records the real time taken into account between 2 commands and replay the same with recorded real time difference.

**Comment by rfk** [comment]
Hi @KK143, since the project is designed for interative use there's no feature like that right now.  It will correctly replay the delay between executing a command and display its output, but the actual execution of commands is triggerd by user input rather than a timer.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
