### ISSUE TITLE
Cannot pause before continuing after a waypoint is encountered.

### ISSUE THREAD

**Issue by jimktrains** [rfk/playitagainsam#20]
Perhaps an example is easier to explain with:

If I'm giving a lecture, I want to be able to have pias enter a command, run the command (pass through the waypoint), and then wait before entering the next command.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
